const item = [
  {
    id: '001',
    image: 'images/js_images/1.jpg',
    company: 'Carlton London',
    product_name: 'Rhodium-Plated CZ Floral Studs',
    original_price: 1045,
    current_price: 606,
    discount_percent: 42,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.5,
        count: 1400,
    },
},
{
    id: '002',
    image: 'images/js_images/2.jpg',
    company: 'CUKOO',
    product_name: 'Women Padded Halter Neck Swimming Dress',
    original_price: 2599,
    current_price: 1507,
    discount_percent: 42,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.3,
        count: 24,
    },
},
{
    id: '003',
    image: 'images/js_images/3.jpg',
    company: 'NUEVOSDAMAS',
    product_name: 'Women Red & White Printed A-Line Knee-Length Skirts',
    original_price: 1599,
    current_price: 495,
    discount_percent: 69,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.1,
        count: 249,
    },
},
{
    id: '004',
    image: 'images/js_images/4.jpg',
    company: 'ADIDAS',
    product_name: 'Indian Cricket ODI Jersey',
    original_price: 999,
    current_price: 999,
    discount_percent: 0,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 5.0,
        count: 10,
    },
},
{
    id: '005',
    image: 'images/js_images/5.jpg',
    company: 'Roadster',
    product_name: 'Pure Cotton T-shirt',
    original_price: 1399,
    current_price: 489,
    discount_percent: 65,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.2,
        count: 3500,
    },
},
{
    id: '006',
    image: 'images/js_images/6.jpg',
    company: 'Nike',
    product_name: 'Men ReactX Running Shoes',
    original_price: 14995,
    current_price: 14995,
    discount_percent: 0,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 0.0,
        count: 0,
    },
},
{
    id: '007',
    image: 'images/js_images/7.jpg',
    company: 'The Indian Garage Co',
    product_name: 'Men Slim Fit Regular Shorts',
    original_price: 1599,
    current_price: 639,
    discount_percent: 60,
    rating: {
        stars: 4.2,
        count: 388,
    },
},
{
    id: '008',
    image: 'images/js_images/8.jpg',
    company: 'Nivea',
    product_name: 'Men Fresh Deodrant 150ml',
    original_price: 285,
    current_price: 142,
    discount_percent: 50,
    return_period: 14,
    delivery_date: '10 Oct 2023',
    rating: {
        stars: 4.2,
        count: 5200,
    },
}
];